### ISSUE TITLE
Store AnyDesk Id -> Name mappings somewhere

### ISSUE THREAD

**Issue by laaksomavrick** [vehikl/vehikl-growth-sessions#109]
There is no central source of truth for documenting the mapping between AnyDesk ids and their colloquial names (e.g. Galang, Mogo Mogo, etc). It would be nice to maintain a list of these for usage in the "Growth Session Location" fields as a dropdown or similar.

**Comment by IthJ** [comment]
This is a great idea. We could also give a warning to get permission of the AnyDesk before choosing as well.
