### ISSUE TITLE
Integrate MobTime!

### ISSUE THREAD

**Issue by FRFlor** [vehikl/vehikl-growth-sessions#11]

**Comment by mrozbarry** [comment]
What sort of integration were you thinking? It's easy enough to link to an ad-hoc timer. You could have an input that looks like `https://mobtime.vehikl.com/ [ ________ ]`. Otherwise I'd need to know exactly what sort of integration you'd want.

**Comment by FRFlor** [comment]
Yeah, I was thinking pretty much that. 

One addition is that this field would come pre-filled with some random string. If the user decides to click on that field, it will automatically clear itself and wait for the user to type a custom name to their timer

**Comment by FRFlor** [comment]
The social card would then have a quick button to open the mobtime on another tab

**Comment by mrozbarry** [comment]
If it's a public mob, it should point to `mobti.me/...` and private should point to `mobtime.vehikl.com/...`
