### ISSUE TITLE
Add Topic Tags

### ISSUE THREAD

**Issue by thelemon2020** [vehikl/vehikl-growth-sessions#169]
It would be neat to be able to add tags/labels to the growth session cards to quickly highlight the technologies/ideas/techniques being used in the growth session.  For example a growth session working on React and Typescript would have small tags at the bottom that would read "React" "Typescript" so attendees can quickly find tech stacks that they are interested in. 

Could be expanded upon later to be used as a search/filter system to only show growth sessions with specific tags.

**Comment by ANDREYDEN** [comment]
@FRFlor I'll start working on this

**Comment by FRFlor** [comment]
Sounds good! Thanks @ANDREYDEN

**Comment by ANDREYDEN** [comment]
@FRFlor, Here's a minimum set of features that we need, I think:
- ability to select tags when creating/editing a GS
- display the tags on the GS card and GS page
- ability to select and filter visible cards by topic

I think topics should be a static list for now and we can add the ability to add new topics later.

**Comment by FRFlor** [comment]
Agreed, 

How do you guys feel about using a multiselect dropdown for finding and adding the tags? 

Something like this: https://vue-multiselect.js.org/

**Comment by FRFlor** [comment]
Some Acceptance criteria I would recommend: 

MVP:
- A growth session should be able to have 0 or more tags assigned to it. 
- A tag should be able to be applied to 0 or more growth sessions.
- The 'name' property in the tags table should be unique.
- Some sanitation of the name would be appreciated before storing in the database (e.g.: remove opening/trailing spaces)
- A user should be able to assign Tags to a growth session upon creating it. 
- A user should be able to assign/remove Tags of a growth session they own.  
- A user should be able to see which Tags a given growth session contain. 

Let me know if you're okay with that. @ANDREYDEN
