### ISSUE TITLE
Join button - Push twice to get two attendee spots

### ISSUE THREAD

**Issue by sebs00** [vehikl/vehikl-growth-sessions#179]
Able to join growth session twice with same user. I suspect there is no check for idempotency regarding the "Join" button checking if a user had already sent a request.

![image](https://user-images.githubusercontent.com/73179860/174856812-60a8173e-7a18-4c06-8bce-46d5472a2c48.png)

This was done by clicking Join twice without waiting for the component to reload to the Leave button.

**Comment by IthJ** [comment]
Is this bug still occurring? I've tried recreating it with Network Throttling but unable to. @sebs00

**Comment by FRFlor** [comment]
We couldn't reproduce the bug.

The app has a policy in place that prevents the same user from joining a given growth session twice in a row.

![image](https://user-images.githubusercontent.com/22578748/201931319-209fa04c-3a92-4a73-a396-ab972bebf784.png)

I don't think this bug applies to the current state of the app. 

If you do re-encounter this bug, please feel free to re-create the issue to let us know.
