### ISSUE TITLE
Unable to use when computer is in a different time zone

### ISSUE THREAD

**Issue by brianhogg** [vehikl/vehikl-growth-sessions#196]
If the computer accessing the growth sessions app is in a different timezone, the growth sessions app breaks.

## Steps to Reproduce

1. Create new growth session for same day at 3:30pm (ET)
2. Switch computer to (say) Spain timezone

### Expected

Join button is displayed either on the growth session listing page, or on the individual page, and visitor is able to join the growth session

### Actual

Join button is not displayed on either the listing page or an individual growth session page, and the visitor is unable to join the growth session

**Comment by brianhogg** [comment]
As a note, the main listing page shows the event on the right date and time, but no join button. The individual growth session page shows the right time, but the date is the day before.

**Comment by FRFlor** [comment]
This issue is now fixed. 

If anyone still experiences issues while accessing the Growth Sessions App from other timezones, let me know.
