### ISSUE TITLE
Create button not clickable on 13" MBP

### ISSUE THREAD

**Issue by brianmclachlin** [vehikl/vehikl-growth-sessions#230]
On smaller monitors the Create button appears below the screen. Not able to scroll to it. Have to reduce zoom to be able to click it.

<img width="1403" alt="Screenshot 2023-11-13 at 2 57 15 PM" src="https://github.com/vehikl/vehikl-growth-sessions/assets/13853211/3bfa056a-e008-41f6-bff0-193110270ad5">

**Comment by ANDREYDEN** [comment]
@brianmclachlin This is now fixed with the new release:

https://github.com/vehikl/vehikl-growth-sessions/assets/25109066/35fe20da-8304-46e7-a1af-c80715ebdf72
