### ISSUE TITLE
Show date on individual growth session page

### ISSUE THREAD

**Issue by johnmal-dev** [vehikl/vehikl-growth-sessions#232]
It would be helpful if the individual growth session pages displayed the session date without requiring a return to the home page.

<img width="844" alt="image" src="https://github.com/vehikl/vehikl-growth-sessions/assets/56036354/2331010c-6c8f-4bcf-bebf-eff26c0ef166">

**Comment by dansoppelsa** [comment]
+1 on this request. I literally came to the repo just now to add this issue :)

**Comment by FRFlor** [comment]
Hey guys, 

Good suggestion, thanks!

We've just merged a quick update to add dates to the page. 

<img width="1456" alt="image" src="https://github.com/vehikl/vehikl-growth-sessions/assets/22578748/a4a5af39-e98b-446f-a422-93bd920d07ce">
