### ISSUE TITLE
Series Templates Suggestion

### ISSUE THREAD

**Issue by joel-smith** [vehikl/vehikl-growth-sessions#233]
It would be useful as a user to be able to easily repeat a series template somehow. Be able to start a growth session as normal but choose to apply a user's pre made series template.

**Comment by FRFlor** [comment]
Hi there Joel,

In the mean time you can use the "clone" button that is below each Growth Session card. This will allow you to make a new one with all the form fields pre-filled with the data of the reference growth session you selected.  

You'll only have to change the Date in this case.

This is pretty handy if you want to host a series of related sessions. 

https://github.com/vehikl/vehikl-growth-sessions/assets/22578748/d04db957-f9ad-4718-9321-18cc6cb07615

**Comment by joel-smith** [comment]
Thanks Felipe! I guess I didn't notice the buton, that's basically all I wanted. Feel free to close this suggestion
