### ISSUE TITLE
[Data] Add Additional Tags

### ISSUE THREAD

**Issue by DeltaBravo** [vehikl/vehikl-growth-sessions#236]
I like the new tag feature and I want even more tags:
- Client Work
- Discussion
- Solo Work

If they are easy to add then also:
- Inertia
- Tailwind
- Nova
- Java

**Comment by FRFlor** [comment]
Hi there @DeltaBravo , I've added these new tags. 

I held on with the "Solo Work" for now because it seems to clash with the spirit behind Growth Sessions in my opinion. 

But let me know if you would like to talk more about this, if you think it's important to add this tag, we can add that in.

**Comment by DeltaBravo** [comment]
Thank you!

Regarding "Solo Work" I would argue that not all growth needs to come from team work.

A growth session in which participants work independently and check in at the end to report progress can add accountability and encourage independent study. Personally I find it easier to learn a new technology outside of the mobbing format. Adding new techniques however definitely benefits from the group format.

All that said, even though solo study is valuable, it does not mean it is appropriate for a growth session.
