### ISSUE TITLE
Individual Growth Session Page Does Not Display Host Details

### ISSUE THREAD

**Issue by dansoppelsa** [vehikl/vehikl-growth-sessions#60]
I noticed there were no details displayed on the individual growth session page about the host. Host information for each session only seems to be available on the weekly overview view.

See below, growth session hosted by Clyaton D'Mello:

![image](https://user-images.githubusercontent.com/933435/101951670-5ffdd980-3bc5-11eb-8181-d301b7d136be.png)

**Comment by FRFlor** [comment]
Thanks Dan!

We added this to the page now, and it should be live in the next deploy.
