### ISSUE TITLE
fix: app thinks I'm both logged in and not logged in

### ISSUE THREAD

**Issue by joshgaber** [vehikl/vehikl-growth-sessions#7]
From the index screen, everything looks fine. However, when I visit individual sessions, the app won't let me join/unjoin or post comments because it thinks I am logged out.

<img width="2560" alt="Screenshot 2020-10-19 at 3 04 46 PM" src="https://user-images.githubusercontent.com/984970/96500273-9d289980-121c-11eb-9050-6875b2804760.png">

**Comment by FRFlor** [comment]
Interesting! Yeah, that should be a quick fix. I'll take a look
