### ISSUE TITLE
fix: new mob modal too small

### ISSUE THREAD

**Issue by joshgaber** [vehikl/vehikl-growth-sessions#8]
Now that the attendee limit has been added, the modal for creating a new event is too small.

<img width="528" alt="Screenshot 2020-10-22 at 10 01 13 AM" src="https://user-images.githubusercontent.com/984970/96882806-acdaf480-144d-11eb-994d-5bcb22c74c7f.png">

**Comment by FRFlor** [comment]
Here was the reason for this: https://github.com/FRFlor/vehikl-growth-sessions/issues/50

I just pushed an update that brings the update feature. That issue has been addressed there. Thanks!
